language: c
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5

python:
  - '3.6'

before_install:
  - pip install --user gcovr

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - cmake .
     - make
     - ./enjector-core-test
     - gcovr -r ./src/core/
