language: c

sudo: required
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

python:
  - '3.6'

before_install:
  - pip install --user gcovr

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - cmake -DCMAKE_BUILD_TYPE=Debug .
     - make
     - ./enjector-core-test
     - gcovr -r ./src/core/
