language: c
compiler:
  - gcc

sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5

matrix:
  include:
  - python: '3.6'
    env: CXX=g++-5 CC=gcc-5 GCOV=gcov-5

install:
- pip install gcovr

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - cmake .
     - make
     - ./enjector-core-test
     - gcovr -r ./src/core/
