language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - cmake
      - cppcheck
      - valgrind

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - cmake .
     - make
     - make coverage
     - make static_check
     - make memory_check
     - ctest
